# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    az --version
    az extension add -n azure-devops
    echo ${AZURE_DEVOPS_CLI_PAT} | az devops login
    az devops configure --defaults organization=https://imademo.visualstudio.com project="DevOps-Patterns" --use-git-aliases true
    az devops project list --output table

  displayName: 'Show list of projects'
  env:
    AZURE_DEVOPS_CLI_PAT: $(System.AccessToken)
